# PART 2

###  :pencil: ***입문 035 :  예외 처리하기***

<br>

자바스크립트 코드를 실행하다 **에러**가 발생하면 그 **즉시 중단**된다. 이를 대비해서 **예외 처리**는 반드시 필요하다. 자바스크립트에서 사용할 수 있는 **예외 처리 방법**에는 **throw 문**과 **try-catch-finally 문**이 있다.

**예외 처리 시** 에러 종류는 크게 **두 가지**로 나뉜다. 

1)  예상치 못한 에러

2)  개발자가 의도한 에러

   여기서 개발자가 의도한 에러란, _코드에서 잘못될 가능성을 예상하고 발생시키는 에러를 의미한다._

먼저, 후자인 경우 **throw 문**을 사용한다.

*throw* 문은 고의로 에러를 발생시켜 예외 상황을 알리는 역할을 한다. 그리고 *thrwo* 문이 실행되면 실행되고 있던 블록을 빠져나간다.

```javascript
// 1.
function checkNumber(val){
    // 2.
    if(typeof val !== 'number') throw '유효하지 않은 값입니다.';
    // 3.
    console.log('숫자형 값으로 확인되었습니다.');
}
// 4.
checkNumber(100);
checkNumber('Wrong type');
console.log('완료');
```

- `1.` 숫자형 값 여부를 확인하는 함수를 선언한다.

- `2.` *typeof val*을 통해 숫자형 값이 아닌 경우, *throw*문을 통해 함수 블록을 빠져나간다.
- `3.` 숫자형이 확인되면 출력되는 문장이다.
- `4.` 숫자형 값 `100`을 넣으면 3라인이 출력된다.

